# Generated by Django 4.2 on 2023-05-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immudbmodel',
            name='ok',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immudbmodel',
            name='key',
            field=models.CharField(default='xjNDTuijKgo4Bm0UTwyOjQeJdSjDJxrAxRZqtYXQs2IPpGTN9xGTueHPUZnAKJabBmQpzen', max_length=255),
        ),
    ]
