# Generated by Django 4.2 on 2023-05-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_immudbmodel_ok_immudbmodel_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('create_multi', models.JSONField(blank=True, null=True)),
                ('key', models.CharField(default='guvtmepYngk1nNqQ98VXZNTiJ8OdqMIzuIeR8fsfHQFmm6apjgiFBlPTVbAIzMJ3MfRYRU7rlp2gVg0F7c', max_length=255)),
                ('nome', models.CharField(max_length=155)),
                ('ok', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ImmudbModel',
        ),
    ]
