# Generated by Django 4.2 on 2023-05-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_test3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TEST3',
        ),
        migrations.DeleteModel(
            name='TEST',
        ),
        migrations.DeleteModel(
            name='TEST2',
        ),
    ]
